# my_config.yaml

# Detection Algorithm
scaler: standardize                   # OPTIONS: standard/minmax
detection_alg: 'iso'                  # OPTIONS: lstm/iso

# Paths
raw_data_path: data/raw/sensor.csv
data_path: data/sdo/sensor.parq
results_path: results/iso1.json

# Log Parameters
logging:
  file_level: DEBUG
  console_level: DEBUG                      # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL

# Data Parameters
cols_to_drop:
  - sensor_15
  - sensor_50

sensors_to_use:
  - sensor_00
  - sensor_02
  - sensor_03
  - sensor_12
  - sensor_18
  - sensor_24
  - sensor_36
  - sensor_40
  - sensor_42
  - sensor_48

# Dataset Creation Parameters
sensor_n: 5                          # 1,2(E),3,4(H),5,6
time_window: '2H'

# Isolation Forest Parameters
shift_alg: 'adtk'                     # ruptures/adtk
contamination: 0.1    # 0.025
n_bkps: 12
c: 4.0
window: 24
batch_size: 1
