# my_config.yaml

# Detection Algorithm
detection_alg: 'iso' # lstm/iso

# Paths
data_path: 'data/sdo/sensor.parq'
results_path: 'results/iso1.json'
model_path: 'models/iso1.pth'

# Log Parameters
logging:
  level: DEBUG                         # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL

# Data Parameters
cols_to_drop:
  - sensor_15
  - sensor_50

sensors_to_use:
  - sensor_00
  - sensor_02
  - sensor_03
  - sensor_12
  - sensor_18
  - sensor_24
  - sensor_36
  - sensor_40
  - sensor_42
  - sensor_48

# Dataset Creation Parameters
sensor_n: 5                           # 1,2(E),3,4(H),5,6
time_window: '5H'
batch_size: 1
overlap: 0
seq_length: 10

# Isolation Forest Parameters
shift_alg: 'adtk'                     # ruptures/adtk
contamination: 0.025
n_bkps: 12
c: 4.0
window: 24

# LSTM Parameters
n_features: 1
hidden_size: 64
num_layers: 2
learning_rate: 0.001
n_epochs: 10
