# my_config.yaml

# Paths
data_path: 'data/sdo/sensor.parq'
results_path: 'results/iso1.json'

# Log Parameters
logging:
  level: DEBUG                         # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL

# Data Parameters
cols_to_drop:
  - sensor_15
  - sensor_50
sensors_to_use:
  - sensor_00
  - sensor_02
  - sensor_03
  - sensor_12
  - sensor_18
  - sensor_24
  - sensor_36
  - sensor_40
  - sensor_42
  - sensor_48

time_window: '5H'

# Model Parameters
shift_alg: 'adtk'                     # ruptures/adtk
sensor_n: 5                           # 1,2(E),3,4(H),5,6
contamination: 0.025
n_bkps: 12
c: 4.0
window: 24
