# Path: my_config.yaml

data_path: 'data/sdo/sensor.parq'
results_path: 'results/iso1.json'

cols_to_drop:
  - sensor_15
  - sensor_50

sensors_to_use:
  - sensor_00
  - sensor_02
  - sensor_03
  - sensor_12
  - sensor_18
  - sensor_24
  - sensor_36
  - sensor_40
  - sensor_42
  - sensor_48

# time_window: '30min'


# # Model Parameters
# model_params:
#   n_estimators: 100
#   max_sample: 0.8
#   max_depth: 3
#   max_features: 0.8
#   contamination: 0.2
#   bootstrap: False
#   random_state: 42
#   n_jobs: -1


time_window: '5H'

shift_alg: 'adtk' # ruptures/adtk
sensor_n: 5
contamination: 0.025
n_bkps: 12
c: 4.0
window: 24

# time_window: '30min'

# shift_alg: 'adtk'     # ruptures/adtk
# sensor_n: 2               # 1,2(E),3,4(H),5,6
# contamination: 0.03
# n_bkps: 6
# c: 128
# window: 2
